### ISSUE TITLE
Update Provider for latest API

### ISSUE THREAD

**Issue by chuckbutler** [scaleway/juju-scaleway#3]
It appears there is a mismatch between the online labs provider and the scaleway API as noted on the [Juju mailing list](https://lists.ubuntu.com/archives/juju/2015-April/005193.html)

**Comment by moul** [comment]
Thank you, I will do the switch now

**Comment by moul** [comment]
@edouardb I switched from onlinelabs to scaleway, can you test and upload the new package ?

**Comment by edouardb** [comment]
Thanks, just try, everything is fine.

**Comment by moul** [comment]
Perfect, can you upload it to pypi servers ?

**Comment by edouardb** [comment]
Done :) https://pypi.python.org/pypi/juju-scaleway/1.0.0

**Comment by moul** [comment]
:+1:, I think, the documentation is oudated on juju's website :)

**Comment by edouardb** [comment]
Do not worry it is already update :) https://jujucharms.com/docs/stable/config-scaleway
